openapi: "3.0.3"
info: 
  title: "Test API"
  version: "1.0.00"
  description: A test API to be used in hosting the API documentation on Github pages.  It models a testing repository
  x-logo: 
    url: "https://transactionjunction.co.za/wp-content/uploads/2020/04/footerlogofull-1.png"

paths:
  /tests:
    get:
      description: Returns a list of tests available in the repository
      responses:
        200: 
          description: A successful response containing a list of tests
          content:
            "application/json":
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/Test"
        404: 
          description: No tests were found
              
components:
  schemas:
    Test:
      type: object
      properties:
        name: 
          type: string
          example: 'Non-zero value'
        summary: 
          type: string
          example: 'Tests for non-zero value of supplied number'
        params: 
          type: object
          properties:
            number: 
              type: integer
              example: 12
